sudo: true
language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
before_script:
- ! ' set -e ;
  pip install ''travis-cargo<0.2'' --user ;
  export PATH=$HOME/.local/bin:$PATH ;
'
script:
- ! ' set -e ;
  travis-cargo build ;
  travis-cargo test ;
  travis-cargo bench ;
  travis-cargo coverage || true ;
'
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
- ! ' set -e ;
  rm -rf target/kcov ;
  rm target/debug/vpncloud-* ;
  cargo test --no-run ;
  kcov/build/src/kcov --exclude-pattern=nptl/sysdeps,/usr/include,/libsodium/,/x86_64-linux-gnu/,/.cargo --coveralls-id=$TRAVIS_JOB_ID target/kcov target/debug/vpncloud-* || true ;
'
notifications:
  email:
    on_success: never
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
